# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8b8094bbae4c5b0db952c3ad01bc98c58fd8eead59aeff1fd29b31297d17bbe07d055e2f483dcd542b4227136bd92559462d6128288eafde5d4a694b9b4af0b

test:
  secret_key_base: 14b48a9e2076a9945bff68f99191fb8a9195e0fb5e9c3372c4d475e7549b647e8d93f21ed6eb9fa8b696b9d14d2eeb3750d1faf8975117ee5f0c848de175e1b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
